use crate::application::{errors::AppError, services::PosterStorage};

pub struct PosterUploadUrlInput {
    pub upload_key: String, // pre-generated by the handler
    pub content_type: String,
    pub expires_in_secs: u32,
}

pub struct PosterUploadUrlOutput {
    pub upload_url: String,
    pub poster_upload_key: String,
}

pub fn get_poster_upload_url(
    storage: &dyn PosterStorage,
    input: PosterUploadUrlInput,
) -> Result<PosterUploadUrlOutput, AppError> {
    let upload_url = storage.presign_upload_url(
        &input.upload_key,
        &input.content_type,
        input.expires_in_secs,
    )?;
    Ok(PosterUploadUrlOutput {
        upload_url,
        poster_upload_key: input.upload_key,
    })
}
