name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/backend-ci.yaml'
  pull_request:
    paths:
      - 'api/**'

env:
  RUST_BACKTRACE: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: api
      - run: cargo fmt -- --check
        working-directory: api

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: api
      - run: cargo build --release --verbose
        working-directory: api

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: api
      - run: cargo test --verbose
        working-directory: api
